###########################################
#                                         #
#   Dockerfile for PEngine Distribution   #
#                                         #
###########################################

FROM    centos:latest
EXPOSE  5051
