name: Linux

on: [push]

jobs:
  build:

    runs-on: centos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.0.100'
    - name: Build with dotnet
      run: dotnet build Solution --configuration Release
    - name: Test with dotnet
      run: dotnet test Solution --configuration Release