name: Linux Debug

on: [push]

jobs:
  build:

    runs-on: centos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.0.100'
    - name: Build with dotnet
      run: dotnet build Solution --configuration Debug
    - name: Test with dotnet
      run: dotnet test Solution --configuration Debug